### ISSUE TITLE
Abandoned GoPasswordCreator

### ISSUE THREAD

**Issue by d3xter** [d3xter/GoPasswordCreator#7]
Hey guys,

I've abandoned this project and Golang a couple of years ago.

So I was wondering if any of you guys would want to take over the project?

I'd update the README so users will know where to go
for an updated version of this project.

@luther9 
@fharding1

**Comment by fharding1** [comment]
Sorry to hear that! If I took over it would probably mean loads of big, breaking changes, so I'll pass, but @luther9 may be interested. If you're wondering why your project is getting lots of attention right now, it's because of hacktoberfest.

**Comment by luther9** [comment]
I'd be glad to take over the project. I'll be sure to update the README.

**Comment by d3xter** [comment]
Alright. Do you guys need me to accept your PR's or do you start working on luther's repository right away?

**Comment by luther9** [comment]
I'm sure I can handle the PRs.

**Comment by d3xter** [comment]
Sorry for the delay. I've updated the README and I'll close all Issues/PRs now.

Thanks for taking it over @luther9 :)
